### ISSUE TITLE
Error wihilw running

### ISSUE THREAD

**Issue by imashwani** [yask123/RedditWallpapers#20]
```

C:\Users\Ashwani\Downloads\Compressed\RedditWallpapers-master>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> redditwallpapers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'redditwallpapers' is not defined
>>>``
```

**Comment by imashwani** [comment]
```
>>> redditwallpapers -sr EarthPorn -sort get_top_from_all  -count 40 -t 10
  File "<stdin>", line 1
    redditwallpapers -sr EarthPorn -sort get_top_from_all  -count 40 -t 10
                                 ^
SyntaxError: invalid syntax
```
if  i try to do t his it still gives error? what can i do
